language: php
sudo: required
php:
  - 8.0

env:
  global:
    - CC_TEST_REPORTER_ID: YOUR_CODECLIMATE_REPORTER_ID
    - CODECOV_TOKEN: YOUR_CODECOV_TOKEN
    - XDEBUG_MODE: coverage

before_script:
  - sudo locale-gen --no-archive fr_CA.UTF-8
  - locale -a
  - echo '' | pecl install apcu
  - echo 'apc.enable_cli="on"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - vendor/bin/phpunit --stderr --verbose --coverage-text

after_script:
  - ls -al
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
  - bash <(curl -s https://codecov.io/bash)
